#!/bin/bash

cat <<EOF > Makefile
CFLAGS=-Werror -Wall -Wextra
LIB=lib$1.a
NAME=\$(LIB)
OBJS=$1.o

all: \$(NAME) "$1"_test

\$(NAME): \$(OBJS)
	ar rcs \$(NAME) \$(OBJS)

clean:
	rm -f \$(OBJS) \$(NAME)

fclean: clean
	rm -f \$(NAME) ft_sub_test

re: fclean
	\$(MAKE)

"$1"_test: "$1"_test.c \$(NAME)
	cc \$(CFLAGS) -o "$1"_test "$1"_test.c \$(NAME) && ./"$1"_test
EOF
