#!/bin/bash

cat <<EOF > Makefile
CFLAGS=-Werror -Wall -Wextra
LIB=lib$1.a
NAME=\$(LIB)
OBJS=$1.o

all: \$(NAME) $1_test

\$(NAME): \$(OBJS)
	ar rcs \$(NAME) \$(OBJS)

clean:
	rm -f \$(OBJS)

fclean: clean
	rm -f \$(NAME) ft_sub_test

re: fclean
	\$(MAKE)

$1_test: $1_test.c \$(NAME)
	cc \$(CFLAGS) -o $1_test $1_test.c \$(NAME) && ./$1_test
EOF
