#!/bin/bash

set -e
if [[ $1 ]]; then
	mkdir $1
	cd $1
	lib $1
	touch "$1"_test.c
	touch $(basename $PWD).c
	header $(basename $PWD)
elif ! [[ -e Makefile ]]; then
	prog
	touch main.c
	touch test.c
	touch $(basename $PWD).c
	header $(basename $PWD)
else
	echo "Makefile exist"
fi
