#!/bin/bash

cat <<EOF > Makefile
CFLAGS=-Werror -Wall -Wextra
LIB=lib$(basename $PWD).a
NAME=$(basename $PWD)
OBJS=$(basename $PWD).o
DEPS= \$LIB # add other deps if needed

all: \$(NAME) test
	./test

\$(NAME): main.c \$(DEPS)
	cc \$(CFLAGS) -o \$(NAME) main.c \$(DEPS)

\$(LIB): \$(OBJS)
	ar rcs \$(LIB) \$(OBJS)

clean:
	rm -f \$(OBJS) \$(DEPS)

fclean: clean
	rm -f \$(NAME) test

re: fclean
	\$(MAKE)

test: test.c \$(DEPS)
	cc \$(CFLAGS) -o test test.c \$(DEPS)

# make other deps here
EOF